server:
  port: 8090

AURORA_HOST: localhost
AURORA_PORT: 5432
AURORA_USERNAME: postgres
AURORA_PASSWORD: postgres
AURORA_DATABASE: users
AURORA_SCHEMA: users

NEO4J_HOST: localhost
NEO4J_PORT: 7687
NEO4J_USERNAME: neo4j
NEO4J_PASSWORD: neo4j
NEO4J_DATABASE: users